name: Build

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 18
      - name: Assemble & Linters
        run: |
          ./gradlew :bottomsheet:testDebugUnitTest :modalsheet:testDebugUnitTest
          ./gradlew lintDebug lintKotlin :demo:assembleDebug apiCheck
      - uses: yutailang0119/action-android-lint@v4.0.1
        name: App Lint errors to annotations
        if: ${{ failure() }}
        continue-on-error: true # lint may be ok
        with:
          xml_path: app/build/reports/lint-results-debug.xml
      - uses: yutailang0119/action-android-lint@v4.0.1
        name: Lib Lint errors to annotations
        if: ${{ failure() }}
        continue-on-error: true # lint may be ok
        with:
          xml_path: lib/build/reports/lint-results-debug.xml
      - name: KTLint errors to annotations
        if: ${{ failure() }}
        run: |
          jq --raw-output '[.[] | ({ f: .file } + ( .errors[] | { l: .line, c: .column, m: .message, r: .rule } )) | "::error file=core/\(.f),line=\(.l),col=\(.c)::\(.m) [\(.r)]" ] | join("\n")' core/build/reports/ktlint/main-lint.json || true
          jq --raw-output '[.[] | ({ f: .file } + ( .errors[] | { l: .line, c: .column, m: .message, r: .rule } )) | "::error file=demo/\(.f),line=\(.l),col=\(.c)::\(.m) [\(.r)]" ] | join("\n")' demo/build/reports/ktlint/main-lint.json || true
